### ISSUE TITLE
support lts-20

### ISSUE THREAD

**Issue by juhp** [jtdaugherty/tart#21]
I am trying to build tart with roughly lts-20: actually for Fedora 38.
One problem is likely that lts now has brick-1.4,
however even before hitting that I get:

```
programs/Theme.hs:30:13: error:
    • No instance for (Data.String.IsString AttrName)
        arising from the literal ‘"error"’
    • In the expression: "error"
      In an equation for ‘errorAttr’: errorAttr = "error"
   |
30 | errorAttr = "error"
   |             ^^^^^^^
```

Maybe some upperbound missing?

The library builds just fine.

**Comment by jtdaugherty** [comment]
I don't quite understand. Are you building `tart` from source? The version in `master` has a fix for the upper bound to avoid this error. (I don't know what you are referring to with "lts-20".)

**Comment by juhp** [comment]
(Well I mean Stackage lts-20, which has brick-1.4.)

Anyway I am trying to build with ghc-9.2.5 and run into the above error with tweaked tart.git.

So do you mean this error is caused by trying to build with newer brick?  Okay I might have guessed :)

**Comment by jtdaugherty** [comment]
> So do you mean this error is caused by trying to build with newer brick?

Yes; the upper bound on `master` (the latest commit, in fact) is required.

**Comment by juhp** [comment]
Any rough timeline when you might support newer brick?

I would probably have to remove tart from Fedora sooner or later, or it may get removed due to the libraries

**Comment by juhp** [comment]
Well I could drop the executable, hehe 😂

**Comment by jtdaugherty** [comment]
I don't have any plans currently since I don't actively maintain this project. I'd be happy to consider a patch if you feel especially motivated to hack on it, though.
